from dotenv import load_dotenv
import os

load_dotenv()

FRONTEND_ADMIN_URL = os.getenv('FRONTEND_ADMIN_URL')
FRONTEND_APP_URL = os.getenv('FRONTEND_APP_URL')
DATABASE_URL = os.getenv('DATABASE_URL')
SECRET_KEY = os.getenv('SECRET_KEY')
ACCESS_TOKEN_EXPIRY=int(os.getenv('ACCESS_TOKEN_EXPIRY'))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv('REFRESH_TOKEN_EXPIRE_DAYS'))
ALGORITHM=os.getenv('ALGORITHM')
RESEND_API_KEY = os.getenv("RESEND_API_KEY")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")